## 파이토치 모듈 

In [83]:
%%writefile pytorch_import.py

import_str = """
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torch.utils.data import DataLoader, TensorDataset

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np

"""


Writing pytorch_import.py


In [9]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torch.utils.data import DataLoader, TensorDataset

In [2]:
torch.__version__

'1.0.1'

## 사이킷트런 모듈

In [12]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

## 판다스와 넘파이 모듈 

In [13]:
import pandas as pd
import numpy as np

In [3]:
import sys

In [4]:
sys.version_info

sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

In [14]:
wine = load_wine()

In [19]:
type(wine)

sklearn.utils.Bunch

## 와인 성분 데이터

In [17]:
wine['data']

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

## 와인의 품종 데이터

In [22]:
wine['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

## 와인 품종 이름

In [25]:
wine['target_names']

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

## 데이터의 설명 

In [20]:
wine['DESCR']

'.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:                     

## 와인 성분명

In [21]:
wine['feature_names']

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [27]:
df_wine = pd.DataFrame(wine.data, columns=wine.feature_names)

In [28]:
df_wine.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [29]:
wine_data = wine.data[:130]

In [30]:
wine_target = wine.target[:130]

## 훈련 데이터와 테스트 데이터로 분리

In [34]:
train_X, test_X, train_Y, test_Y = train_test_split(wine_data, wine_target, test_size=0.2)

In [35]:
len(train_X)

104

In [36]:
len(test_X)

26

## 텐서로 변환하기

In [37]:
train_X = torch.from_numpy(train_X).float()

In [38]:
train_Y = torch.from_numpy(train_Y).long()

In [41]:
train_X.shape, train_Y.shape

(torch.Size([104, 13]), torch.Size([104]))

In [39]:
test_X = torch.from_numpy(test_X).float()

In [40]:
test_Y = torch.from_numpy(test_Y).long()

In [42]:
test_X.shape, test_Y.shape

(torch.Size([26, 13]), torch.Size([26]))

## 텐서 데이터 세트로 통합하기

In [43]:
train = TensorDataset(train_X, train_Y)

In [44]:
train[0]

(tensor([1.3410e+01, 3.8400e+00, 2.1200e+00, 1.8800e+01, 9.0000e+01, 2.4500e+00,
         2.6800e+00, 2.7000e-01, 1.4800e+00, 4.2800e+00, 9.1000e-01, 3.0000e+00,
         1.0350e+03]), tensor(0))

### 두 개의 데이터를 하나로 통합해주는 작업 수행

In [51]:
type(train)

torch.utils.data.dataset.TensorDataset

In [49]:
train.tensors[0].shape

torch.Size([104, 13])

In [50]:
train.tensors[1].shape

torch.Size([104])

## 미니배치로 분할

In [53]:
train_loader = DataLoader(train, batch_size=16, shuffle=True)

In [54]:
type(train_loader)

torch.utils.data.dataloader.DataLoader

### 입력으로 받은 데이터를 보관하는 장소 

In [58]:
train_loader.dataset.tensors[0].shape

torch.Size([104, 13])

In [59]:
train_loader.batch_size

16

In [64]:
train_loader.batch_sampler

In [66]:
train_loader.batch_sampler.sampler

In [68]:
train_loader.batch_sampler.sampler.data_source.tensors[0].shape

torch.Size([104, 13])

## 신경망 구성

In [69]:
class Net(nn.Module) :
    def __init__(self) :
        super(Net, self).__init__()
        self.fc1 = nn.Linear(13,96)
        self.fc2 = nn.Linear(96,2)
        
    def forward(self,x) :
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x) # deprecated 

In [70]:
model = Net()

## 오차 함수 및 최적화 객체 만들기

In [71]:
criterion = nn.CrossEntropyLoss()

In [73]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

## 학습 

In [78]:
for epoch in range(300) :
    total_loss = 0
    for train_x, train_y in train_loader :
        train_x, train_y = Variable(train_x), Variable(train_y) # 계산 그래프 구성
        optimizer.zero_grad() # 경사 초기화
        
        output = model(train_x) # 순전파 계산
        
        loss = criterion(output, train_y) # 오차 계산
        
        loss.backward() # 역전파 계산
        optimizer.step() # 가중치 업데이트
        
        total_loss += loss.item()  # 누적오차 계산
        
    if (epoch+1) % 50 == 0 :
        print(epoch+1, total_loss)

C:\Users\dahlmoon\Anaconda3\envs\pytorch_cpu\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  # Remove the CWD from sys.path while we load stuff.


50 4.825241327285767
100 4.837199866771698
150 4.800600051879883
200 4.813867509365082
250 4.825129389762878
300 4.8362075090408325


## 테스트 

In [80]:
# 계산그래프 구성
test_x, test_y = Variable(test_X), Variable(test_Y)

result = torch.max(model(test_x).data, 1)[1]

C:\Users\dahlmoon\Anaconda3\envs\pytorch_cpu\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  # Remove the CWD from sys.path while we load stuff.


In [82]:
accuracy = sum(test_y.data.numpy() == result.numpy()) / len(test_y.data.numpy())
print(accuracy)

0.5384615384615384
