## import 문장을 별도의 파일로 만들어서 처리

In [1]:
import pytorch_import

exec(pytorch_import.import_str)

In [2]:
x = Variable(torch.randn(5, 5))
y = Variable(torch.randn(5, 5))
z = Variable(torch.randn(5, 5), requires_grad=True)
a = x + y
a.requires_grad


False

In [3]:
b = a + z
b.requires_grad

True

In [4]:
x_ = torch.randn(5, 5, requires_grad=True)

In [5]:
x_.grad

In [6]:
c = x_ + x

In [7]:
c.grad

In [8]:
xx = torch.ones(2,2, requires_grad=True)

In [9]:
xx

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
xx.grad

In [11]:
yy = xx + 2

In [12]:
yy

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [13]:
yy.grad

In [14]:
yy.grad_fn

In [15]:
zz = yy * yy * 3 
out = zz.mean()

In [16]:
zz

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [17]:
out

tensor(27., grad_fn=<MeanBackward1>)

In [18]:
out.backward()

In [19]:
zz.grad

In [20]:
xx.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [21]:
yy.grad

In [22]:
out.grad