In [1]:
import torch

In [3]:
x = torch.tensor((1,2,3))

In [4]:
dir(x)

['__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__setstate_

In [6]:
x.ndimension()

1

In [7]:
x.size()

torch.Size([3])

In [8]:
x.shape

torch.Size([3])

In [20]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

In [14]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
y = x.view(9)

In [16]:
x is y

False

In [17]:
import numpy as np

In [18]:
np.may_share_memory(x,y)

True

In [13]:
x.view(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
help(x.view)

Help on built-in function view:

view(...) method of torch.Tensor instance
    view(*shape) -> Tensor
    
    Returns a new tensor with the same data as the :attr:`self` tensor but of a
    different :attr:`shape`.
    
    The returned tensor shares the same data and must have the same number
    of elements, but may have a different size. For a tensor to be viewed, the new
    view size must be compatible with its original size and stride, i.e., each new
    view dimension must either be a subspace of an original dimension, or only span
    across original dimensions :math:`d, d+1, \dots, d+k` that satisfy the following
    contiguity-like condition that :math:`\forall i = 0, \dots, k-1`,
    
    .. math::
    
      \text{stride}[i] = \text{stride}[i+1] \times \text{size}[i+1]
    
    Otherwise, :meth:`contiguous` needs to be called before the tensor can be
    viewed. See also: :meth:`reshape`, which returns a view if the shapes are
    compatible, and copies (equivalent to call

In [21]:
z = torch.unsqueeze(x, 0)


In [22]:
z

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [23]:
np.may_share_memory(x,z)

True

In [25]:
z.size()

torch.Size([1, 3, 3])

In [26]:
a = torch.squeeze(x)


In [27]:
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
np.may_share_memory(x,a)

True

In [30]:
w = torch.randn(5,3, dtype = torch.float)
x = torch.tensor([[1.0,2.0], [3.0,4.0], [5.0,6.0]])

b = torch.randn(5,2, dtype = torch.float)
wx = torch.mm(w,x)

result = wx + b

print(x)
print(w)
print(b)
print(wx)
print(result)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 1.8492,  0.6484,  0.5243],
        [ 1.6804, -0.7767, -0.7794],
        [-0.0313,  0.7954, -0.6203],
        [ 2.0149,  0.4923, -0.5575],
        [ 0.4382,  0.7693,  0.8514]])
tensor([[ 5.7594e-01,  9.0458e-01],
        [-2.6474e+00,  2.2282e-01],
        [-4.7553e-02, -6.5503e-01],
        [ 1.4121e+00, -4.4077e-01],
        [-1.4259e-03,  9.4915e-01]])
tensor([[ 6.4161,  9.4380],
        [-4.5469, -4.4226],
        [-0.7469, -0.6031],
        [ 0.7046,  2.6544],
        [ 7.0031,  9.0620]])
tensor([[ 6.9920, 10.3426],
        [-7.1943, -4.1998],
        [-0.7944, -1.2582],
        [ 2.1167,  2.2136],
        [ 7.0017, 10.0112]])


In [45]:
w = torch.tensor(1., requires_grad=True)

In [46]:
a = w*3

In [39]:
a

tensor(3., grad_fn=<MulBackward0>)

In [40]:
a.backward()
print(w.grad)


tensor(3.)


In [34]:
a

tensor(3., grad_fn=<MulBackward0>)

In [41]:
w

tensor(1., requires_grad=True)

In [42]:
a

tensor(3., grad_fn=<MulBackward0>)

In [47]:
l = a**2

In [48]:
l.backward()
print('l을 w로 미분한 값은 {}'.format(w.grad))

l을 w로 미분한 값은 18.0
